# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37694ce4b9a77408dadb1bbe8119dae3f9fb33f8baa966ff5c1dfc8801c173907067abbde98b0e56545e1ada89eb878c495f50663d86e43ec5ff54230ea80165

test:
  secret_key_base: 79e24df78cf16c3c709761f09076ea27212d64f57e98a632747780afab1be89fcc27ad0228da59554d509e5aad79b20058a23716050672accdd22bbebfd78670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
